[package]
name = "ffizz-passby"
description = "FFI helpers for implementing pass-by-value and pass-by-pointer"
repository = "https://github.com/djmitche/ffizz"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
uuid = { version = "^1.1.2", features = ["v4"] }
